### ISSUE TITLE
Feature request: add option to allow getting partitions for a specific cluster (or for multiple clusters)

### ISSUE THREAD

**Issue by itkovian** [mercanca/spart#3]
`spart` right now does not allow specifying a cluster to look up partitions from.

Would it be possible to add such an option? E.g., `-c <clustername>` (or ideally, a comma separated list of cluster names), to allow an overview of all partitions on all clusters?

**Comment by mercanca** [comment]
I am looking a solution to do your request, but slurm api don't have any functions to do (I can not find). Without modifing the code to use slurm development libraries, instead of the slurm api which I use, I can't find a solution to get partition list for a cluster list.

**Comment by itkovian** [comment]
Thanks for the swift reply. Is there no way to get it for a specific cluster either? Feel free to close the issue then :)

**Comment by mercanca** [comment]
It is not your original request, but I added a -c parameter to show partitions from federated clusters to the last update I did today. The -c parameter don't take any cluster name. Because of I don't have a access to multi-cluster environment, I couldn't test this version. If you can test and paste output to here, it would be great.
